[features]
seeds = false
skip-lint = false
[programs.localnet]
backend = "BrZ7wezEyEWncfSc2vu9dRs1yZP9uw9M7atpki9ovnL1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vivi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
