[features]
seeds = false
skip-lint = false
[programs.devnet]
backend = "FrhgU1YQivVRKdbW9iFGfBiVYLSkuCuM8ZyjXiMrtNF1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/vivi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
